"use client";
import {useMemo,useState} from "react"; import {Search,Download,SlidersHorizontal} from "lucide-react"; import {Company} from "../lib/types"; import {api} from "../lib/api";
export default function IntelligenceTable({rows,onOpen,onRefresh}:{rows:Company[];onOpen:(id:string)=>void;onRefresh:()=>void}){
 const [search,setSearch]=useState("");const [min,setMin]=useState(false);const [selected,setSelected]=useState<string[]>([]);const [op,setOp]=useState("VERIFY_SECURITY_LEADERSHIP");const [msg,setMsg]=useState("");
 const filtered=useMemo(()=>rows.filter(r=>(r.name+" "+r.domain+" "+r.location).toLowerCase().includes(search.toLowerCase())&&(!min||(r.score??0)>75)),[rows,search,min]);
 async function enrich(){if(!selected.length)return;const r=await api.enrich(selected,op);setMsg(`${r.estimated_unit_cost} units queued`);await api.runEnrich(r.enrichment_job_id);onRefresh()}
 return <section className="border border-slate-800 rounded-xl overflow-hidden"><div className="p-3 border-b border-slate-800 flex gap-2 items-center"><div className="relative flex-1"><Search size={14} className="absolute left-3 top-2.5 text-slate-500"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search accounts…" className="w-full bg-slate-900 rounded-md pl-9 pr-3 py-2 text-xs outline-none"/></div><button onClick={()=>setMin(!min)} className={`text-xs px-3 py-2 rounded-md border ${min?"border-slate-500 bg-slate-800":"border-slate-800"}`}><SlidersHorizontal size={14} className="inline mr-1"/>ICP &gt;75</button><select value={op} onChange={e=>setOp(e.target.value)} className="bg-slate-900 border border-slate-800 text-xs rounded-md px-2"><option>VERIFY_SECURITY_LEADERSHIP</option><option>TECH_STACK_DETECT</option><option>RECENT_FUNDING</option></select><button onClick={enrich} className="text-xs bg-white text-black px-3 py-2 rounded-md">Enrich selected</button><a href={api.exportCsv()} className="p-2 border border-slate-800 rounded-md" title="CSV"><Download size={14}/></a></div>{msg&&<div className="px-4 py-2 text-xs text-slate-400">{msg}</div>}
<table className="w-full text-left text-xs"><thead className="bg-slate-950 text-slate-500"><tr><th className="p-3 w-8"></th><th className="p-3">Company</th><th className="p-3">Headcount</th><th className="p-3">Location</th><th className="p-3">ICP Score</th><th className="p-3">Decision maker</th><th className="p-3">Evidence</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t border-slate-900 hover:bg-slate-900/50 cursor-pointer" onClick={()=>onOpen(r.id)}><td className="p-3" onClick={e=>e.stopPropagation()}><input type="checkbox" checked={selected.includes(r.id)} onChange={e=>setSelected(e.target.checked?[...selected,r.id]:selected.filter(x=>x!==r.id))}/></td><td className="p-3"><div className="font-medium">{r.name}</div><div className="text-slate-500">{r.domain}</div></td><td className="p-3">{r.employee_range}</td><td className="p-3">{r.location}</td><td className="p-3"><span className={`px-2 py-1 rounded ${r.score!==null&&r.score>75?"bg-emerald-500/15 text-emerald-300":"bg-slate-800 text-slate-300"}`}>{r.score?.toFixed(1)??"—"}</span></td><td className="p-3">{r.top_decision_maker??"—"}</td><td className="p-3"><span className={r.evidence_status==="Conflicting"?"text-amber-400":r.evidence_status==="Verified"?"text-emerald-400":"text-slate-500"}>{r.evidence_status} · {r.evidence_count}</span></td></tr>)}</tbody></table></section>
}
